#!/usr/bin/env php
<?php

use Daerisimber\Config;
use Symfony\Component\Console\Application;

define('ROOT_THEME_DIR', __DIR__);

require __DIR__ . '/vendor/autoload.php';

$application = new Application();

$config = require __DIR__ . '/src/config/app.php';

if (isset($config['commands']) && is_array($config['commands'])) {
    foreach ($config['commands'] as $commandClass) {
        if (class_exists($commandClass)) {
            $application->add(new $commandClass());
        }
    }
}

$application->run();
