<?php

return [
    'menus' => [
        'main_menu' => __('Main Menu'),
        'footer_menu' => __('Footer Menu'),
    ],
    'themes_remove_supports' => [
        'core-block-patterns',
    ],
    'themes_supports' => [
        'automatic-feed-links' => true,
        'menus' => true,
        'post-thumbnails' => true,
        'custom-logo' => true,
        'wp-block-styles' => true,
        'title-tag' => true,
        'editor-styles' => true,
        'align-wide' => true,
        'anchor' => true,
        'html5' =>
            [
                'comment-form',
                'comment-list',
                'gallery',
                'caption',
            ]
    ],
    'upload_mimes' => [
        'svg' => 'image/svg+xml',
        //"json" => "text/plain",
    ],
    'should_load_remote_block_patterns' => false,
    'blocks_blacklist' => [
        /*====text====*/
            //'core/paragraph',
            //'core/heading',
            //'core/list',
            //'core/list-item',
            //'core/quote',
            //'core/code',
            //'core/preformatted',
            //'core/pullquote',
            //'core/table',
            //'core/verse',
            //'core/footnotes',
            //media
            //'core/image',
            //'core/gallery',
            //'core/audio',
            //'core/cover',
            //'core/file',
            //'core/media-text',
            //'core/video',
            /*====design====*/
            'core/buttons',
            'core/button',
            //'core/group',
            //'core/row',
            //'core/stack',
            'core/more',
            'core/nextpage',
            //'core/separator',
            'core/spacer',
            /*====widgets====*/
            'core/archives',
            'core/calendar',
            'core/categories',
            'core/html',
            'core/latest-comments',
            'core/latest-posts',
            'core/page-list',
            'core/page-list-item',
            'core/rss',
            'core/search',
            'core/shortcode',
            'core/social-links',
            'core/social-link',
            'core/tag-cloud',
            /*====theme====*/
            'core/navigation',
            'core/site-logo',
            'core/site-title',
            'core/site-tagline',
            'core/query',
            'core/query-title',
            'core/query-pagination',
            'core/query-pagination-numbers',
            'core/query-pagination-previous',
            'core/query-pagination-next',
            'core/query-no-results',
            'core/posts-list',
            'core/avatar',
            'core/post-title',
            'core/post-excerpt',
            'core/post-featured-image',
            'core/post-content',
            'core/post-author',
            'core/post-author-name',
            'core/post-author-biography',
            'core/post-time-to-read',
            'core/post-comments-count',
            'core/post-comments-link',
            'core/post-date',
            'core/post-terms',
            'core/post-navigation-link',
            'core/read-more',
            'core/post-template',
            'core/comments',
            'core/comment-author-name',
            'core/comment-content',
            'core/comment-date',
            'core/comment-edit-link',
            'core/comment-reply-link',
            'core/comment-template',
            'core/comments-title',
            'core/comments-pagination',
            'core/comments-pagination-next',
            'core/comments-pagination-numbers',
            'core/comments-pagination-previous',
            'core/post-comments-form',
            'core/loginout',
            'core/term-description',
            'core/term-count',
            'core/term-name',
            'core/term-template',
            'core/terms-query',
            'core/breadcrumbs',
            /*====embeds====*/
            //'core/embed',
    ]
];
